package com.tacstargame.combat.unit.stats;

public enum ModificatorStat implements Stat {
	DAMAGEDONE,
	DAMAGETAKEN,
	HEALINGDONE,
	HEALINGTAKEN,
	RESOURCECOSTS,
	MAXENERGY,
	SHADOWDAMAGEDONE,
	FIREDAMAGEDONE,
	ICEDAMAGEDONE,
	WINDDAMAGEDONE,
	EARTHDAMAGEDONE,
	LIGHTDAMAGEDONE,
}
